on: [push, pull_request]

name: Continuous integration

jobs:
  format-check:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          clang-format --version
          ./cicd/format.sh check ./cicd/clang-format-configure
